######################################################################
# Automatically generated by qmake (2.01a) ? 5? 19 18:30:26 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/include.
LIBS += -lwiringPi

# Input
HEADERS += main.h
SOURCES += main.cpp painter.cpp print.cpp sensor.cpp
